version: '3'
services:
  jms:
    image: vromero/activemq-artemis
    ports:
      - 8161:8161
      - 61616:61616
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  eureka:
    image: sfgbeerworks/sfg-brewery-eureka
    ports:
      - 8761:8761 
  config:
    image: sfgbeerworks/sfg-brewery-config
    ports:
      - 8888:8888
    depends_on:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@localhost:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
  inventory-service:
    image: sfgbeerworks/sfg-brewery-inventory-service
    ports:
      - 8082:8082
    depends_on:
      - eureka
      - config
      - jms  
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@localhost:8761/eureka
      SPRING_PROFILES_ACTIVE: local-discovery,localmysql
      SPRING_ZIPKIN_BASEURL: http://zipkin
      SPRING_ARTEMIS_HOST: jms
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/beerorderservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
    restart: on-failure
  inventory-failover: 
    image: sfgbeerworks/sfg-brewery-inventory-failover
    ports:
      - 8083:8083
    depends_on:
      - eureka
      - config
      - jms
      - inventory-service  
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@localhost:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
    restart: on-failure
  beer-service:
    image: sfgbeerworks/sfg-brewery-beer-service
    ports:
      - 8080:8080
    depends_on:
      - eureka
      - config
      - jms  
      - inventory-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@localhost:8761/eureka
      SPRING_PROFILES_ACTIVE: local-discovery,localmysql
      SPRING_ZIPKIN_BASEURL: http://zipkin
      SPRING_ARTEMIS_HOST: jms
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/beerorderservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
    restart: on-failure
  order-service:
    image: sfgbeerworks/sfg-brewery-beer-service
    ports:
      - 8081:8081
    depends_on:
      - eureka
      - config
      - jms  
      - beer-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@localhost:8761/eureka
      SPRING_PROFILES_ACTIVE: local-discovery,localmysql
      SPRING_ZIPKIN_BASEURL: http://zipkin
      SPRING_ARTEMIS_HOST: jms
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/beerorderservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
    restart: on-failure